# Definición de constantes para el proyecto

DIRECTORIO_BASE       = '..'
DIRECTORIO_DATOS      = f'{DIRECTORIO_BASE}/Datos'
DIRECTORIO_RESULTADOS = f'{DIRECTORIO_BASE}/Resultados'
DIRECTORIO_MODELOS    = f'{DIRECTORIO_BASE}/Modelos'
DIRECTORIO_LIB        = f'{DIRECTORIO_BASE}/Lib'
DIRECTORIO_GRAFICAS   = f'{DIRECTORIO_BASE}/Gráficas'